CREATE TABLE palpite (
	id int PRIMARY KEY AUTO_INCREMENT,
	id_jogador int NOT NULL,
	id_rodada int NOT NULL,
	id_partida int NOT NULL,
	resultado VARCHAR(20) NOT NULL,
	CONSTRAINT FK_JOGADOR_PALPITE FOREIGN KEY (id_jogador) REFERENCES usuario(id),
	CONSTRAINT FK_RODADA_PALPITE FOREIGN KEY (id_rodada) REFERENCES rodada(id),
	CONSTRAINT FK_PARTIDA_PALPITE FOREIGN KEY (id_partida) REFERENCES partida(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;